const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_RESPONSE = "LOGIN_RESPONSE";
const REGISTER_REQUEST = "REGISTER_REQUEST";
const REGISTER_RESPONSE = "REGISTER_RESPONSE";

export { LOGIN_REQUEST, LOGIN_RESPONSE, REGISTER_REQUEST, REGISTER_RESPONSE };
